### ISSUE TITLE
Suspicious asignment of polarizabilities

### ISSUE THREAD

**Issue by kostalv** [TinkerTools/poltype2#15]
Hello,

I recently used your Poltype2 code to parametrize an organic molecule, namely N-methylsulfamate. However, when I check the final.key file containing the parameters, I see comments that poltype2 identified the three terminal oxygens with sulfur atoms (sulfur and the terminal oxygens indeed share the same polarizability parameter). The same situation happened also to the nitrogen atom that was assigned with parameters from hydrogen on non-aromatic nitrogen and the carbon atom that was identified as hydrogen on non-aromatic carbon.

Could you please help me to figure out where could be the potential issue? As I got it correctly, polarizabilities are taken from your database and only multipoles undergo the fitting to the qm-based electrostatic potential (in my parametrization I can see unique set of multipoles at each atom).

I also attach an archive containing the initial geometry in .sdf format, .ini file and the final.key file the outputted parameters.
[poltype2-NMSM.zip](https://github.com/TinkerTools/poltype2/files/9600428/poltype2-NMSM.zip)

Thank you in advance for any advice.

**Comment by bdw2292** [comment]
Thank you for being vigilant and checking results to make sure they make sense. This is a somewhat more serious issue/bug introduced a few months ago while I was trying to handle a special case of polarizability assignment for molecules that are charged and also have resonance. It works fine now.
