### ISSUE TITLE
atomic polarizabilities assignment

### ISSUE THREAD

**Issue by kostalv** [TinkerTools/poltype2#16]
Hello,

I was recently checking amoeba parameters for my molecule parametrized by the poltype2 protocol and I came across something I cannot resolve. Apparently, the atomic polarizabilities are assigned according to the file ~/path_to_poltype2/ParameterFiles/amoeba21polarize.prm. However,  in your recent paper: https://pubs.acs.org/doi/pdf/10.1021/acs.jcim.1c01307 in Table 1, there are reported different values (especially if you have a look at values for sulfur and oxygens bonded to sulfur atoms).

Could you please comment on that, especially which set of parameters is more relevant or am I missing something?

Thank you in advance.

**Comment by bdw2292** [comment]
Hello,

The last column of table 1 values are all in amoeba21polarize.prm. Do you have a more specific value in mind, from what I see they are all in there (last column of table 1).

**Comment by kostalv** [comment]
thank you, I found the table I wanted in the SI.

**Comment by bdw2292** [comment]
Glad to hear it, sorry should have been more clear there is an additional table I appended (the spacing is different in the actual file) for the charged groups.
