### ISSUE TITLE
Can't run example hydration free energy test

### ISSUE THREAD

**Issue by todacp** [TinkerTools/poltype2#18]
Hello:
I've successfully compiled the latest version of the code, along with Tinker Version 8.10.4  October 2022.
When I try to run the example in the hydrationfreenergy of phenol folder (poltype2/Examples/HydrationFreeEnergy/phenol), it fails with the following error:
Traceback (most recent call last):
  _File "/home/user/codes/poltype2/PoltypeModules/poltype.py", line 7485, in <module>
    RunPoltype()
  File "/home/user/codes/poltype2/PoltypeModules/poltype.py", line 7459, in RunPoltype
    poltype=PolarizableTyper()
  File "<string>", line 376, in __init__
  File "/home/user/codes/poltype2/PoltypeModules/poltype.py", line 1229, in __post_init__
    self.MolecularDynamics()
  File "/home/user/codes/poltype2/PoltypeModules/poltype.py", line 2129, in MolecularDynamics
    ann.main(self)
  File "/home/user/codes/poltype2/PoltypeModules/annihilation.py", line 37, in main
    box.BoxSetupProtocol(poltype)
  File "/home/user/codes/poltype2/PoltypeModules/boxsetup.py", line 831, in BoxSetupProtocol
    newfilename=CreateSolventBox(poltype,subaaxis,subbaxis,subcaxis,subwater,'water.xyz',key)
  File "/home/user/codes/poltype2/PoltypeModules/boxsetup.py", line 433, in CreateSolventBox
    submit.call_subsystem(poltype,cmdstr,wait=True)
  File "/home/user/codes/poltype2/PoltypeModules/submitjobs.py", line 117, in call_subsystem
    raise ValueError("ERROR: " + cmdstr+' '+'path'+' = '+os.getcwd())
ValueError: ERROR: xyzedit.x water.xyz -k MD_solv_config.key < xyzedit.in path = /home/user/codes/poltype2/Examples/HydrationFreeEnergy/phenol_

Upon running the offending xyzedit.x command, it seems like the options may have changed... namely:
 The Tinker XYZ File Editing Utility Can :

    (1) Offset the Numbers of the Current Atoms
    (2) Remove User Specified Individual Atoms
    (3) Remove User Specified Types of Atoms
    (4) Delete Inactive Atoms Beyond Cutoff Range
    (5) Insertion of Individual Specified Atoms
    (6) Replace Old Atom Type with a New Type
    (7) Assign Connectivities for Linear Chain
    (8) Assign Connectivities Based on Distance
    (9) Assign Atom Types for BASIC Force Field
   (10) Transfer Atom Types from Another Structure
   (11) Convert Units from Bohrs to Angstroms
   (12) Invert thru Origin to Give Mirror Image
   (13) Translate All Atoms by an X,Y,Z-Vector
   (14) Translate Center of Mass to the Origin
   (15) Translate a Specified Atom to the Origin
   (16) Translate and Rotate to Inertial Frame
   (17) Rotate All Atoms Around a Specified Axis
   (18) Move to Specified Rigid Body Coordinates
   (19) Move Stray Molecules into Periodic Box
   (20) Trim a Periodic Box to a Smaller Size
   (21) Make Truncated Octahedron from Cubic Box
   (22) Make Rhombic Dodecahedron from Cubic Box
   (23) Append a Second XYZ File to Current One
   (24) Create and Fill a Periodic Boundary Box
   (25) Soak Current Molecule in Box of Solvent
   (26) Place Monoatomic Ions around a Solute

Does the boxsetup.py script need updating?

Thanks!

**Comment by bdw2292** [comment]
Thank you, should be fixed now.
