### ISSUE TITLE
Poltype hangs with complex after new pull

### ISSUE THREAD

**Issue by BJWiley233** [TinkerTools/poltype2#19]
Hi Brandon,

I just made a fresh pull of Poltype and now I am trying to run a simulation drug ligand and it just hangs here at the very beginning.  It started to run before I did the pull but got an error with just made me decide to pull despite was probably a pdb error.
```
Calling: analyze /storage1/fs1/bolton/Active/projects/BWILEYtest/poltype2/VersionFiles/water.xyz -k /storage1/fs1/bolton/Active/projects/BWILEYtest/poltype2/VersionFiles/water.key e> version.out
```

This is the input poltype.ini file.  Has anything changed to where this is now incorrect input?  I am also getting a weird file called `blank.txt` that is only 1 byte in size
```
complexedproteinpdbname=P00519_WT_fill.B99990001.tinker.pdb
numproc=16
ligandxyzfilenamelist=imatinib.xyz,dasatinib.xyz
keyfilenamelist=imatinib.key,dasatinib.key
submitlocally=False
```

**Comment by BJWiley233** [comment]
Ok it seems like the call to `xyzedit` is whats hanging.  Looks like this was newly added functionality in function DetermineXYZEditOptions to probably take care of if/when Dr. Ponder changes it again 😄.

If I call the first call of it without outputting to file xyzout.txt like this it expects a new line to be entered to exit.  Not sure if the currently code worked for your but the only way for it to work for me was this code
```
echo -e "\n" | xyzedit /storage1/fs1/bolton/Active/projects/BWt.txtest/poltype2/VersionFiles/water.xyz > xyzout
```

So this worked when I changed the code to this:
```
cmdstr='echo -e "\n" |' + self.xyzeditpath+' '+os.path.abspath(os.path.join(self.poltypepath, os.pardir))+r'/VersionFiles/'+'water.xyz'+' '+'>'+' '+xyzout
```

**Comment by BJWiley233** [comment]
Ah also this line [here](https://github.com/TinkerTools/poltype2/blob/master/PoltypeModules/boxsetup.py#L683) should be
```
temp.write(poltype.xyzeditappendvalue+'\n')
```
instead of just
```
temp.write(xyzeditappendvalue+'\n')
```

**Comment by BJWiley233** [comment]
If you are interested in what my PDB error was, when I submitted a complexpdb file with the CONECT lines added to it for each of the two ligands, poltype ended up creating a completed structure with a -3.000 charge.  I can supply input files for the simulation.  I confirmed the CONECT structures were back when I had to optimize the molecules because else the SDF bonding was off and these needed to be correct before running poltype to optimize them.

![image](https://user-images.githubusercontent.com/26236052/200170391-4391dd58-b981-431b-9f37-366644ae64c7.png)

**Comment by bdw2292** [comment]
Thanks for the catch, yeah exactly trying to keep independent from tinker version as much as possible. I'll have to see files and more details to understand what the problem is.

**Comment by BJWiley233** [comment]
Gotcha.  Here are the input files.
https://drive.google.com/file/d/1HqGBYWRwY5t0FrAZk3297kFkHBRthDBP/view?usp=sharing

**Comment by jayponder** [comment]
Sorry, this is probably my fault... There is a new option (#10) added to the current GitHub version of the XYZEDIT program in Tinker. So any scripts or parts of Poltype that use XYZEDIT options numbered 10 to greater will need to increment the option number by one.

**Comment by bdw2292** [comment]
It’s no worries or problem @jayponder , I’m assuming the text entry for each xyzedit option won’t change and hardcode that instead of hard coding option numbers now.

**Comment by bdw2292** [comment]
It appears that in part of the CONECT record for the input pdb, there are some letters attached to one of the numbers (manual edit mistake?) so I just removed those from the file and now the box is being generated.

**Comment by BJWiley233** [comment]
OMG yes I guess I was running `cp` command in some terminal but was in the pdb file.  Happens all the time!
