### ISSUE TITLE
ValueError: torsion parameters are all zero torsion

### ISSUE THREAD

**Issue by D16ERG** [TinkerTools/poltype2#2]
Dear all,

For a supramolecular inclusion complex; I have tried to parameterize [beta-cyclodextrin](https://en.wikipedia.org/wiki/Cyclodextrin). Initially, I tried to parameterize the whole beta-cyclodextrin molecule. Unfortunately, just optimizing this geometry takes unfavorably long. On the one hand; I could attempt to use the [BrianQC](https://www.brianqc.com) [GPU interface](https://psicode.org/psi4manual/master/brianqc.html) to [Psi4](https://psicode.org/installs/latest/). Since my trial licence to BrianQC has expired however; I have decided to use a different strategy. Beta-cyclodextrin is a cyclic oligosaccharide, composed of seven α-D-glucopyranoside subunits. Without exceptions; these subunits are linked through α-1,4 glycosidic bonds. At face value; it seems to be the case that cyclodextrins can be parameterized by reusing parameters from two linked subunits. I therefore intend to reuse the atom-type values from the parameterized dimer.
So far; this scheme stranded with the final torsional parameters of the dimer. It seems that the zero torsions from key_4 could not be fitted to the calculated torsions of the fragments. Hence the ValueError and zero torsions in key_5. Is there a shorthand solution to this problem or does this particular case conflict with the existing parameterization code?

https://we.tl/t-BLbnluY3JK

Target supramolecular complex
![target supramolecular complex](https://user-images.githubusercontent.com/79671816/130478380-27dcc72f-1d00-48b6-9a1e-80984d720536.png)

dimer repetition unit
![cyclodextrin dimer](https://user-images.githubusercontent.com/79671816/130480952-d4f8f6d1-12c6-4459-9ba9-c8c95a772445.png)

Kind regards,

Didier

**Comment by bdw2292** [comment]
Hey,

So the issue is that poltype does not pass all of the arguments from parent to fragment ( I only pass ones I think are important). So things like atmidx (changing starting number of atomindex), for example I have never needed, but I have passed this along to fragment jobs. Basically, the fragments still think they should start at 401 type numbers instead of 701.
