### ISSUE TITLE
Poltype parameterization fails at potential (6) Fit Electrostatic Parameters to Target Grid

### ISSUE THREAD

**Issue by D16ERG** [TinkerTools/poltype2#20]
Poltype crashes during the parameterization of a 65-atom molecule.
The direct cause for the crash seems to originate from Poledit its failure
to fully assign polarization groups to the molecule. Parameterization thus
fails with the following log entries:

```
 Undefined Atomic Multipole Parameters :

 Warning, No Multipole Parameters for Atom     41
 Warning, No Multipole Parameters for Atom     42
 Warning, No Multipole Parameters for Atom     43
 Warning, No Multipole Parameters for Atom     44

 Additional Atomic Dipole Polarizability Parameters :

     Atom Type           Alpha       Thole     Group Atom Types

         401             1.334       0.390         428
         402             1.334       0.390         429
         403             1.750       0.390         404  430
         404             1.750       0.390         403
         405             1.750       0.390         431
         406             1.750       0.390         432
         407             1.750       0.390         414
         408             1.334       0.390         433
         409             1.334       0.390         410
         410             0.837       0.390         409  411
         411             1.334       0.390         410  434
         412             1.334       0.390         435
         413             1.334       0.390         436
         414             2.064       0.390         407
         415             1.334       0.390         437
         416             1.334       0.390         426
         426             0.496       0.390         416
         417             1.334       0.390         438
         418             1.334       0.390         439
         419             1.334       0.390         427
         427             0.496       0.390         419
         420             1.334       0.390         421
         421             0.812       0.390         420  422
         422             1.620       0.390         421  434
         423             1.334       0.390         440
         424             1.334       0.390
         425             1.415       0.390         441
         428             0.496       0.390         401
         429             0.496       0.390         402
         430             0.696       0.390         403
         431             0.696       0.390         405
         432             0.432       0.390         406
         433             0.496       0.390         408
         434             0.496       0.390         411
         435             0.496       0.390         412
         436             0.496       0.390         413
         437             0.496       0.390         415
         438             0.496       0.390         417
         439             0.496       0.390         418
         440             0.496       0.390         423
         441             0.480       0.390         425


 POLARGRP  --  Check Polarization Groups for Atoms       26 and       56

 POLARGRP  --  Check Polarization Groups for Atoms       26 and       57

 POLARGRP  --  Check Polarization Groups for Atoms       27 and       58

 POLARGRP  --  Check Polarization Groups for Atoms       27 and       59

 Tinker is Unable to Continue; Terminating the Current Calculation
Tue Dec 27 12:22:24 2022 Traceback (most recent call last):
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 7735, in RunPoltype
    poltype.main()
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 3427, in main
    params= self.GenerateParameters()
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 4698, in GenerateParameters
    combinedxyz,combinedpot=esp.ElectrostaticPotentialFitting(self,xyzfnamelist,keyfnamelist,potnamelist)
  File "/home/didier/poltype/PoltypeModules/electrostaticpotential.py", line 518, in ElectrostaticPotentialFitting
    shutil.copy(combinedxyz.replace('.xyz','.key'),poltype.key3fnamefrompot)
  File "/home/didier/anaconda3/envs/poltype/lib/python3.9/shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/didier/anaconda3/envs/poltype/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'combined.key' 
```

So far, I have tried rerunning the perl script and potential program to no avail.
The full parameterization directory has been archived and uploaded towards
the following WeTransfer link:
[https://we.tl/t-kkC35zNHYH](https://we.tl/t-kkC35zNHYH)

**Comment by bdw2292** [comment]
Hello, thanks for the catch. Issues with recent changes to symmetry detection, if you pull and delete all tinker related files and restart it should be fine.

**Comment by D16ERG** [comment]
Awesome, I will confirm the completed parameterization.

**Comment by D16ERG** [comment]
I reran the parameterization from scratch. The above issue has been resolved. Only on 
the fragment jobs 4_5_Index_0 and 6_7_Index_0 poltype 2 halts on an IndexError. This 
error message is as follows:


`Traceback (most recent call last):
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 7909, in RunPoltype
    poltype.main()
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 3441, in main
    params= self.GenerateParameters()
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 4559, in GenerateParameters
    indextocoordslist=self.GenerateMaxSymmetryConformer(m,mol)
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 3841, in GenerateMaxSymmetryConformer
    rdkitmol=self.GenerateConformers(rdkitmol,mol)
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 3789, in GenerateConformers
    firsttor=rottors[0]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 7909, in RunPoltype
    poltype.main()
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 3441, in main
    params= self.GenerateParameters()
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 4559, in GenerateParameters
    indextocoordslist=self.GenerateMaxSymmetryConformer(m,mol)
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 3841, in GenerateMaxSymmetryConformer
    rdkitmol=self.GenerateConformers(rdkitmol,mol) 
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 3789, in GenerateConformers
    firsttor=rottors[0]
IndexError: list index out of range
`

The crashing fragment jobs can be found in the uploaded project directory. All other working
fragment jobs have been performed individually from their sub directories.

[https://we.tl/t-jQRwVOXe0B](https://we.tl/t-jQRwVOXe0B)
