### ISSUE TITLE
ATTACH  --  Too many 1-3 Connected Atoms Attached to Atom

### ISSUE THREAD

**Issue by anessler** [TinkerTools/poltype2#29]
As far as I can tell the poledit executable does not like the GDMA output... I had run this job (5,5'-Dinitro-2,2'-dithiodipyridine) previously without the new GDMA flags and it finished successfully. I have one other PolType job that terminated similarly (4-Methyl-2-nitroacetanilide), so maybe something with the nitro group? Any suggestions would be greatly appreciated! Please find the corresponding files [here](https://iowa-my.sharepoint.com/:u:/g/personal/anessler_uiowa_edu/EbLE2sYmsXVPsLOZIvb-jIsBw9Fk7kVNFcVrmC9-xTJKPA?e=KakB6L).

**Comment by leucinw** [comment]
Hi Aaron,
I briefly checked the files you provided. The optimized structures (opt_1.xyz) are very different between the `run1` and `try1` directories. Then if you look at the input files (*.psi4), they are different in convergence criteria and PCM method. So my suggestion is to manually run some psi4 jobs by changing these keywords to see what causes the difference.

**Comment by jayponder** [comment]
I took just the GDMA output you provided for this molecule (UFAGIS) and ran it through the current GitHub version of the Tinker POLEDIT program. It appears to run correctly. So I think the problem is not in POLEDIT itself. Perhaps the issue is somewhere in what PolType is giving to POLEDIT? As Chengwen suggests above, you might try some manually run Psi4 output.

**Comment by leucinw** [comment]
Besides Jay's suggestion, this is related to another GitHub issue we saw yesterday. In the latest commit https://github.com/TinkerTools/poltype2/commit/002dc827b2756064a5b7f55304728ba18dbb3fff I have ruled out the nitro group as Zwitter ion, so PCM will be turned off for your molecules. You should not have a problem optimizing the structures.

**Comment by anessler** [comment]
I reran this molecule after [b18298b](https://github.com/TinkerTools/poltype2/commit/b18298bb4b8e0a0d82e533008362e38d13590326) and the job finished successfully!  Thank you very much for all of your help!
