### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by D16ERG** [TinkerTools/poltype2#3]
Dear Bryan,

While parameterizing hexamethylated maltose; Poltype encountered an error during the creation of fragmented jobs.
The IndexError is somehow related to the setup of torsions. The exact output of this error is not visible in the logs but
instead visible in the terminal:

Traceback (most recent call last):
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 1937, in RunPoltype
    poltype.main()
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 1154, in main
    params= self.GenerateParameters()
  File "/home/didier/poltype/PoltypeModules/poltype.py", line 1789, in GenerateParameters
    equivalentrotbndindexarrays,rotbndindextoringtor=frag.SpawnPoltypeJobsForFragments(self,rotbndindextoparentindextofragindex,rotbndindextofragment,rotbndindextofragmentfilepath,equivalentrotbndindexarrays,rotbndindextoringtor,equivalentrotbndindexmaps)
  File "/home/didier/poltype/PoltypeModules/fragmenter.py", line 676, in SpawnPoltypeJobsForFragments
    equivclasskey=torgen.get_class_key(poltype,equivparenttor[0],equivparenttor[1],equivparenttor[2],equivparenttor[3])
IndexError: list index out of range

The relevant poltype job has been compressed and uploaded to wetransfer. It is temporarily available at:
https://we.tl/t-DeUR4GIGZh
Can you make sense out of it?

Kind regards,

Didier

**Comment by D16ERG** [comment]
The error seems Dear Bryan,

The above error has been resolved. When the current parameterization finishes; I will closed this issue.

Kind regards,

Didier

**Comment by bdw2292** [comment]
No need to close, I have not finished final tests. I believe it is fixed,
but waiting for QM to finish so I can double check everything :)

**Comment by bdw2292** [comment]
Fixed

**Comment by bdw2292** [comment]
Please pull latest version
