### ISSUE TITLE
Running Poltype2 for Nitrobenzene

### ISSUE THREAD

**Issue by cdpoon** [TinkerTools/poltype2#30]
I have been creating Docker images for Poltype2.  When building the Docker images, it pulls the latest version of Poltype2 from GitHub.  So, I have a Poltype2 Docker image based on the version of Poltype2 pulling on 24 May 2023.  Using that Docker container, I am able to run the water example without any problem.  Then, running Poltype2 with the Docker container for benzene also finishes nicely.  However, when I add a nitro group to the benzene ring to become nitrobenzene, Poltype2 keeps running optimization and will not converge.  Even after several hours, it is not able to finish up optimization and move on.

When I use the Poltype2 Docker image built on 22 December 2022, that version of Poltype2 has no problem running nitrobenzene and finishes in a few minutes.

In the Docker images, psi4 is installed and no Gaussian.  I can see that the Temp/name-opt_1.psi4 file has changed quite a bit between the 2 versions I am testing.

Are there tricks to run nitrobenzene using the latest version of Poltype2?  If there are, would you mind sharing those tricks?

CD Poon.
University of North Carolina at Chapel Hill

**Comment by zjing7** [comment]
Hi,
This is partly due to a bug in Poltype that incorrectly clarifies nitrobenzene as a zwitterion and turns on PCM.
A workaround is to manually disable PCM by using the option `dontusepcm`

**Comment by cdpoon** [comment]
Thanks so much, adding the option dontusepcm fixes it.
 
In the documentation, I see another option, optpcm.  I have tried "optpcm=FALSE" and it does not work.

**Comment by leucinw** [comment]
I also pushed a `fix` to rule out nitro group as Zwitter ion, so PCM is not used. This can be seen here: https://github.com/TinkerTools/poltype2/commit/002dc827b2756064a5b7f55304728ba18dbb3fff

**Comment by cdpoon** [comment]
Yes, the update works for nitrobenzene without option "dontusepcm".
