### ISSUE TITLE
Error with poledit

### ISSUE THREAD

**Issue by mayank-kohli** [TinkerTools/poltype2#38]
Hi,

I followed the steps mentioned in the README file, but When I am running the parametrization command I am getting following error:

`ERROR: Cannot find Tinker poledit.x executable`

Can you suggest where I might be going wrong

**Comment by leucinw** [comment]
As the error says, poltype is complaining about missing poledit.x executable
If you have installed tinker8, simply add the path where poledit.x locates to your $PATH
If not, you need to first install tinker8 then do the above.

**Comment by mayank-kohli** [comment]
It worked

Thank you
