### ISSUE TITLE
Spatial::LSTCAP

### ISSUE THREAD

**Issue by mayank-kohli** [TinkerTools/poltype2#39]
Hi, 

I am stuck at few places 

1. I am getting the following error:

GPU Device :  Setting Device ID to 0 from GPU utilization
 Backtrace
    1  analyze9                                                      0x17c64d
    2  analyze9                                                      0x164a54
    3  analyze9                                                      0x15c5a9
    4  analyze9                                                      0x18ca77
    5  analyze9                                                      0x19014f
    6  analyze9                                                      0x1915c4
    7  analyze9                                                      0x20f8d
    8  /lib/x86_64-linux-gnu/libc.so.6                               __libc_start_main
    9  analyze9                                                      0x21ebe
 Terminating with uncaught exception :  An internal array in Spatial requested 12994 elements, but only 7968 (48*166) were allocated. Please increase Spatial::LSTCAP (current value 48) so as to make Spatial::LSTCAP*166 >= 12994.

2. I have Zinc ion in my system, but in `uncomplexed.pdb` there is no zinc ion

3. The `complex_receptoronly.pdb` is looking like this:
![image](https://github.com/TinkerTools/poltype2/assets/64058587/33f94b25-9ff5-4a69-80ca-a8059c5f4e04)

**Comment by leucinw** [comment]
It seems that the 1st error is about Tinker9, not Poltype. I suggest you report to Tinker9 
For the 2 and 3, I am not sure what are the issues. Do they relate to Poltype?

**Comment by mayank-kohli** [comment]
the issue 3 is happening after the complex formation, which I guess is leading to issue number 1 and the protein has a zinc ion but it not showing in any of the output.

**Comment by leucinw** [comment]
If you are using poltype to generate the simulation box, I suggest you use other tools, such as xyzedit.x in Tinker or CHARMM-GUI box generator. 
We want to limit poltype's function to `small molecule parameter generator for AMOEBA and AMOEBA+ models`. Other functions have not been extensively tested and will be removed in the future.

**Comment by mayank-kohli** [comment]
oh okay, I ll generate with the suggested tools.

Thank you
