### ISSUE TITLE
installation missing prtdcd.f

### ISSUE THREAD

**Issue by agoliaei** [TinkerTools/poltype2#43]
Hi,
I hope you are well.
I am trying to install following this: https://github.com/TinkerTools/poltype2/blob/master/README/README_INSTALL.MD
after installing tinker, when I try to install tinker9, the cmake step gives me this error:
-- Configuring done
CMake Error at ext/interface/CMakeLists.txt:6 (add_library):
  Cannot find source file:

    ../source/prtdcd.f

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc

CMake Error at ext/interface/CMakeLists.txt:6 (add_library):
  No SOURCES given to target: tinkerObjF

I was wondering if you could kindly help me. Where can I find this file? Looks like it is missing on the github page.

**Comment by leucinw** [comment]
I am sure you will get more professional help if you paste this to the Github site of [Tinker9](https://github.com/TinkerTools/Tinker9)

**Comment by agoliaei** [comment]
Thank you.
I will.
