### ISSUE TITLE
retaining original coordinates of input molecules

### ISSUE THREAD

**Issue by blakemertz** [TinkerTools/poltype2#44]
I am trying to set up some MD runs to simulate a series of small molecules against a reference protein target using AMOEBA, and was able to generate parameter files for the small molecules in poltype2. However, when I compare my final.xyz and my input.sdf against each other, final.xyz has been translated away from the original position of input.sdf. My input.sdf was docked into the binding site of the target protein, so I was really hoping to avoid having to align my final.xyz to my input.sdf in order to set up my MD simulations.

The description of aligning a ligand to the coordinates of an unoccupied protein in the documentation [here](https://github.com/TinkerTools/poltype2?tab=readme-ov-file#protein-input-preparation), but the impression I get from that documentation is that defining 
```
complexedproteinpdbname=pdb3srd.pdb
uncomplexedproteinpdbname=3srd_filled.BL00020001_final.pdb
```
still assumes that your ligand is docked in the correct spatial coordinates with respect to the protein. If I am missing something in my understanding of the documentation, I apologize.

**Comment by leucinw** [comment]
Hi Blake,
If I understand your question correctly, the simplest way to fix it is to use the coordinates you want and paste the connectivity and atom type from final.xyz
As for the functionalities besides `parametrize a small molecule` in poltype, they are not extensively tested and will be removed from poltype.

**Comment by pren** [comment]
If the atom order is the same, you just need copy the atom type column.

Thanks,
Pengyu
________________________________

**Comment by blakemertz** [comment]
@leucinw @pren thank you for the clarification -- copying the coordinates from my original sdf into the final.xyz worked.
