### ISSUE TITLE
Poltype2 gets stuck after OPT_1 step; Restart overwrites normally terminated *opt_1.log

### ISSUE THREAD

**Issue by jacekkozuch** [TinkerTools/poltype2#5]
Hi, 

I am observing that poltype2 gets stuck directly after the first optimization step for a few larger molecules than methanol (e.g. penicillin G, p-coumaric acid). The opt_1.log file shows normal termination (last few lines):

>  Job cpu time:       0 days  5 hours 53 minutes 58.0 seconds.
>  Elapsed time:       0 days  0 hours 56 minutes 22.6 seconds.
>  File lengths (MBytes):  RWF=     82 Int=      0 D2E=      0 Chk=     13 Scr=      1
>  Normal termination of Gaussian 16 at Sat Nov 13 01:40:57 2021.

poltype.log shows:

> Sat Nov 13 00:44:29 2021 Running on host: c142.curta.zedat.fu-berlin.de
> Sat Nov 13 00:44:29 2021 NEED QM Density Matrix: Executing Gaussian Opt and SP
> Sat Nov 13 00:44:29 2021 Percent of jobs finished 0.0
> Sat Nov 13 00:44:29 2021 Calling: GAUSS_SCRDIR=/scratch/jkozuch/Gau-PCC /trinity/shared/software/gaussian/g16_A03/g16/g16 PCC-opt_1.com path = /home/jkozuch/Param/PCC

At this point nothing happens for hours. I then restart poltype to continue from here, but the normally terminated *_opt_1.log is not recognized and is overwritten, as a new OPT_1 calculation starts.

My poltype.ini looks as follows:
structure=PCC.sdf
totalcharge=-1
numproc=8
maxmem=64GB
maxdisk=500GB
atmidx=455
use_gaus
rotalltors

The MeOH example with essentially the same input doesn't have an issue at this point. However, it seems to get stuck in the torsion section (unless there's something happening in the background). I also just checked methyl propionate as a smaller molecule with two torsions, instead of the one in MeOH) and I have the same issue - opt_1 is finished; nothing else happens after that; restart starts from scratch and overwrites opt_1.log.

-------------------------------------------------------------------

Addition after I wrote this. I tried the series MeOH, EtOH, PrOH, and BuOH, making the molecule longer by one CH3 and I observe the issue described above with BuOH, where the first three molecules work. Everything is similar as stated above. 

Best,
Jacek

**Comment by bdw2292** [comment]
Hello,

Please try the latest commit from Friday, we observed some issues from very
recent changes.

As for the deleting of opt.log, this typically only happens if the
coordinates from molecule-opt.xyz (cartesian xyz directly from QM log file)
file and the coordinates from molecule.xyz (tinker xyz) are not the same.
This can happen if user changed opt method (then everything else needs to
be removed after). As an example, the SymmetryWater and SymmetryMethane
both have this issue if you inspect their coordinate files, probably
because when these files were originally generated we had a different opt
method (so user might thing to remove all *xyz*, *key* and qm log files
*log*, however the tinker xyz file comes from GDMA output, so more files
actually need to be removed. You can see in this case the Methane and Water
examples online are using DFT (we had gone through a period we were using
this for OPT), but now we use MP2 as our default.

**Comment by jacekkozuch** [comment]
Regarding the second point:
The deleting of opt.log happens (or rather happened in the previous commit) before there were any xyz files present. 

Regarding the first one:
So, I just cloned the new commit. And now I get what you're describing with PrOH (not with MeOH, tho!). OPT_1 and DMA are succesful and then aufger GDMA I get the XYZ issue you're describing. BTW: my sbatch_submit file get also deleted by the new poltype commit (in every case, also MeOH). I do not change any opt methods; it's still the same poltype.ini file I'm running.

**Comment by bdw2292** [comment]
Sounds great.

We recently turned on a feature that deletes all non QM files ( exceptions, .log ,.ini , .mol and .sdf) this probably explains why your submission script is deleted. This is a good feature to have turned on during development so as to make it easier when people may get stuck between "bad commits", that for example generate tinker files that were not intended.

One possibility is you can move the Submission script to another directory, or we can come up with some input that excludes a filename.
________________________________

**Comment by bdw2292** [comment]
Also, .dat and .chk files excluded
________________________________

**Comment by jacekkozuch** [comment]
Ok, I understand, I'm placing the submit file now elsewhere, so that's fine. However, because of this deletion due different xyz structure, I can't get PrOH parameterized. If I try to follow what going on in poltype.log, before it's deleted I see:

> Sat Nov 13 16:22:35 2021 Running on host: c170.curta.zedat.fu-berlin.de
> Sat Nov 13 16:22:35 2021 NEED QM Density Matrix: Executing Gaussian Opt and SP
> Sat Nov 13 16:22:35 2021 Percent of jobs finished 0.0
> Sat Nov 13 16:22:35 2021 Calling: GAUSS_SCRDIR=/scratch/jkozuch/Gau-PrOH /trinity/shared/software/gaussian/g16_A03/g16/g16 PrOH-opt_1.com path = /home/jkozuch/Param/test/PrOH
> Sat Nov 13 16:22:49 2021 Normal termination: logfile=/home/jkozuch/Param/test/PrOH/PrOH-opt_1.log path=/home/jkozuch/Param/test/PrOH
> Sat Nov 13 16:22:49 2021 Calling: /trinity/shared/software/gaussian/g16_A03/g16/formchk PrOH-opt_1.chk path = /home/jkozuch/Param/test/PrOH
>  Read checkpoint file PrOH-opt_1.chk
>  Write formatted file PrOH-opt_1.fchk
>  FChkPn:  Coordinates translated and rotated.
>  FChkPn:  Coordinates match /B/ after translation and rotation.
> Sat Nov 13 16:22:49 2021 Searching database for parameters
> Sat Nov 13 16:23:07 2021 Percent of jobs finished 0.0
> Sat Nov 13 16:23:07 2021 Calling: /trinity/shared/software/gaussian/g16_A03/g16/g16 PrOH-dma.com path = /home/jkozuch/Param/test/PrOH
> Sat Nov 13 16:23:13 2021 Normal termination: logfile=/home/jkozuch/Param/test/PrOH/PrOH-dma.log path=/home/jkozuch/Param/test/PrOH
> Sat Nov 13 16:23:14 2021 Calling: /trinity/shared/software/gaussian/g16_A03/g16/g16 PrOH-dma.com path = /home/jkozuch/Param/test/PrOH

Then everything is deleted except for:

poltype.ini
PrOH.gdmaout
PrOH.sdf
PrOH-dma.fchk

and then it's over.

Again, MeOH doesn't show this problem. So, how do I prepare the sdf file of PrOH to avoid this problem?

**Comment by bdw2292** [comment]
I am unable to reproduce your error with 1-proponal, could you send over a
zipped folder of your files?

Also, there is no need for "rotalltors". We have a pretty good criteria for
deciding when its okay to transfer torsion parameters from the database
(the rule of thumb is if the databasematch contains 4 torsion atoms +
neighbors of those 4 atoms

**Comment by jacekkozuch** [comment]
Attached a zip file with:
- PrOH stuck after OPT
- PrOH crash and deletion after GDMA
- PrOH crash and deletion after GDMA - when directly rerunning after previous crash

Unfortunately, you won't find the poltype.log nor the submit.out files, they got deleted.

Thanks for looking into it!

[test.zip](https://github.com/TinkerTools/poltype2/files/7532404/test.zip)

**Comment by bdw2292** [comment]
Hello,

In your PrOH_stuckafteropt folder: I am unable to reproduce the getting
stuck, it just goes to dma, then esp, then generates key files.
For the PrOH_crashaftergdma folder: I do see the dma.log file kinda stops
rather abruptly at the top without an error? This might be some local
gaussian environment issue?  I will attach the full dma.log here. (also in
that folder the opt log files do not exist, so opt will start first before
dma).

**Comment by bdw2292** [comment]
Now I see your issue in first folder of opt being repeated, this is due to
a couple of reasons
1) we made recent changes to how we submit gaussian /psi4 jobs . Sometimes
psi4 will crash and hang, while poltype will wait for a return signal from
the subprocess module that never gets returned, so in some cases we instead
parse the output log for a termination signal and check for errors.
2) Gaussian sometimes has things in their log files such as "Error  RMS
Error" (even if there is term signal) , then poltype sees that and thinks
its not finished and needs to redo it. I will add a special case in the
error catching part.

**Comment by bdw2292** [comment]
I just added the exception, and now I observe in your first folder that
opt.log is not repeated.

**Comment by jacekkozuch** [comment]
Perfect, thx. I suppose it's enough if I just replace poltype.py, correct? Or should I clone it entirely?

**Comment by bdw2292** [comment]
Yes either way is fine, which ever is easiest for you. Git pull is also nice if you have ssh keys set up.
________________________________

**Comment by jacekkozuch** [comment]
Hmm, not really sure what is going on. I'm confused about this. 

So, indeed opt is not deleted anymore, so thanks for this change. However, 1-propanol is still a problem for some strange reason. Even stranger is that methanol (despite running esp with PSI4, even though use_gaus was specified), ethanol and 1-butanol work; but 1-prop crashes directly before the esp QM calculation. I attached a zip with the remaining files from the 1-propanol run (it's a acually two combined runs if you're wondering; I renamed it to 1-propanol when I managed to grab the log files before they disappeared), in case you see something special about the log files or the gdma step.

BTW: now, the poltype.log file is also deleted when things restart. I suppose an exception might be good here to keep it and append the next run.

I'll go ahead with my larger molecules and see if the original problem is solved now.

[PrOH.zip](https://github.com/TinkerTools/poltype2/files/7532834/PrOH.zip)

**Comment by bdw2292** [comment]
Yes there appears to be some issue when you execute gaussian on dma.log, i cannot reproduce it but I saw the file termination abruptly without an error from your zipped files.


Poltyoe log file is not appended, just rewritten every time poltyor starts (its not being deleted by function, just overwritten).
________________________________

**Comment by bdw2292** [comment]
You can try running the gaussian command from terminal manually and see if it gives the same result.
________________________________

**Comment by jacekkozuch** [comment]
You're talking about these few seconds?
```
Sat Nov 13 23:00:35 2021 Calling: /trinity/shared/software/gaussian/g16_A03/g16/g16 1-propanol-dma.com path = /home/jkozuch/Param/PrOH
Sat Nov 13 23:00:48 2021 Normal termination: logfile=/home/jkozuch/Param/PrOH/1-propanol-dma.log path=/home/jkozuch/Param/PrOH
Sat Nov 13 23:00:48 2021 Calling: /trinity/shared/software/gaussian/g16_A03/g16/g16 1-propanol-dma.com path = /home/jkozuch/Param/PrOH
```

That's just to be a quick one. When I submit it manually it's also that quick.
```
 Job cpu time:       0 days  0 hours  0 minutes 21.9 seconds.
 Elapsed time:       0 days  0 hours  0 minutes  6.4 seconds.
 File lengths (MBytes):  RWF=     10 Int=      0 D2E=      0 Chk=      2 Scr=      1
 Normal termination of Gaussian 16 at Sat Nov 13 23:28:48 2021.
```
Also the poltype.log shows that it went through GDMA and poledit and only after that it crashes. But it maybe a Gaussian issue. Are you using also g16_A03? I think we only have this one on the HPC. I just tried it with PSI4 and it ran through the entire procedure. I'll ask our HPC ppl if we have another version/release available.

**Comment by bdw2292** [comment]
We are using g09. I believe it must be gaussan related since the log file I saw earlier was very strange, it said something about writing a file, then didn't get to any computations, just sort of stopped.
________________________________

**Comment by jacekkozuch** [comment]
Ok, this make sense now. I'll ask the HPC people here, if it's possible to make a g09 version available. I understand that you don't have g16 to test it - I will let you if I manage to compare both.

I'll add "g16 vs g09" to the title and close this issue. Thanks for the help!

**Comment by CallumFrEllis** [comment]
Hi Poltype team, 
I am trying to parameterise a modified glutamine molecule, and I am getting the same error as this, with poltype.py completing the g09 calculation and generating the opt_1.log file, with Gaussian finishing normally, but then it is hanging indefinitely, poltype.ini and .log files below. The opt_1.log file does have 'RMS Error' in the text but this was fixed?

Can't see any glaring errors so any suggestions would be great appriciated. Installed this week so should be the latest commit. 

Thanks, 

Callum

opt-1.log:
                          -- CICERO
 Job cpu time:       0 days  4 hours 39 minutes 44.3 seconds.
 File lengths (MBytes):  RWF=   1152 Int=      0 D2E=      0 Chk=     24 Scr=     16
 Normal termination of Gaussian 09 at Wed Jan  8 11:30:55 2025.
                                                                        
poltype.log:
Wed Jan  8 11:19:04 2025 Atom Type Classification
Wed Jan  8 11:19:04 2025 Calling: python "/mainfs/scratch/ce3g12/2ndRotation/3rd_year/poltype/master/PoltypeModules/lConformerGenerator.py" -i poltype_methyl_ester.sdf
Wed Jan  8 11:19:14 2025 Running on host: red313.cluster.local
Wed Jan  8 11:19:14 2025 QM Geometry Optimization
Wed Jan  8 11:19:15 2025 Submitting: GAUSS_SCRDIR=/scratch/ce3g12/Gau-poltype_methyl_ester /local/software/gaussian/g09/g09 poltype_methyl_ester-opt_1.com path = /mainfs/scratch/ce3g12/2ndRotation/3rd_year/poltype/master/PoltypeModules/methyl_ester_gas/Temp


poltype.ini:
structure=poltype_methyl_ester.sdf
addhydrogens=True
use_gaus
