### ISSUE TITLE
Torsion fit pngs - inconsistency in 0 vs. 360 deg?

### ISSUE THREAD

**Issue by jacekkozuch** [TinkerTools/poltype2#7]
Hi,

I'm not really sure if I'm just misunderstanding something, but there seems to be a strange offset in some of the png-output files from the torsion fit. See attached energy-png files, in particular, those for the torsion 5-1 and 5-8. Here the red data starts at 0 deg, while blue and others at ca. 30 deg. I assume there's a difference in definition when an torsion is 0 and when 360 deg.

I'm not sure if this is just an issue in representation or also something in the code that may cause issues with the torsion fit - the red curve is shifted in respect to the other ones.

Also, since I'm asking about torsions:
I'm not sure that I'm reading the torsion results correctly. 
- Just from the log file, I see that TFH-fit...png files are generated much earlier than energy.pngs. I understand that the "fit.png" are the prefit (or intermediate step) results. Correct?
- The energy.png files are those important to determine which torsion parameters are good and which not, correct?

I've to stay that I'm still confused about the splines in the energy plots (is it a cumulative RMSD in reference to the energy at lowest angle?). I think in the previous Poltype2 version, the splines went through the data points, which made it much easier to decipher, which torsion is parameterized well or not. Maybe you could bring back the previous representation in addition to the current one? 

Thanks!
Jacek

![TFH-energy-5-1](https://user-images.githubusercontent.com/72883367/155956400-15e6bbca-fd6b-45ca-bb8a-2dec0919e733.png)
![TFH-energy-5-8](https://user-images.githubusercontent.com/72883367/155956403-b2fb81bb-7a61-4394-86bf-bfd4e292c7c8.png)
![TFH-energy-11-8](https://user-images.githubusercontent.com/72883367/155956405-60b2ba3a-bf50-4770-be0b-6af5438440c7.png)
![TFH-energy-11-14](https://user-images.githubusercontent.com/72883367/155956406-c50ecf22-ed93-4df0-be76-80f471c4b9de.png)
![TFH-fit-5-1](https://user-images.githubusercontent.com/72883367/155956408-ccee06c3-f7d4-4763-b20d-98152d361df1.png)
![TFH-fit-5-8](https://user-images.githubusercontent.com/72883367/155956409-3d7da38d-30b5-42c3-96d4-a4da2bf9e5bc.png)
![TFH-fit-11-8](https://user-images.githubusercontent.com/72883367/155956412-71533602-585e-499f-aa24-a50a0e834a8d.png)
![TFH-fit-11-14](https://user-images.githubusercontent.com/72883367/155956413-c9bc038a-3c2f-4827-b3f4-d17a5d2c9ab4.png)

**Comment by bdw2292** [comment]
Hello,

Yes that is all correct. I dont remember the details exactly, but at some point I was having some spline issues perhaps due to differing array sizes and ended up trying to fix it by removing points that are the same from the input into the spline (which of course not good if you have very symmetrical molecule with same energy values). I have reverted back to the original splines. 

- Brandon

**Comment by jacekkozuch** [comment]
Thx Brandon. That helped and the torsion fit is now much faster in reaching conversion.

However, in the case of the 1-5-torsion I see that the red curve is going from 30 to 360, whereas the others from 0 to 330. If I compare the 1-5-torsion with the 5-8-torsion, I don't see any reason why 1-5 should have worse RSMDs. Could this be an artefact of data points at 0 and 360 missing?


![MFH-energy-8-11](https://user-images.githubusercontent.com/72883367/156023720-2c2c0c99-6bb6-4d77-a9bb-6346a667dd96.png)
![MFH-energy-14-11](https://user-images.githubusercontent.com/72883367/156023723-36f42ed0-20f4-4745-8827-fa1ab8f69a91.png)
![MFH-energy-1-5](https://user-images.githubusercontent.com/72883367/156023716-bbf8e357-6ac0-4743-ab3a-7bfd77525f98.png)
![MFH-energy-8-5](https://user-images.githubusercontent.com/72883367/156023719-559af6d1-3a29-426a-bab8-9cd191f5a609.png)

**Comment by bdw2292** [comment]
The third image looks incorrect, could you attach all input and output files? I will take a peak.

**Comment by jacekkozuch** [comment]
I just reran everything from scratch and it looks good now. Don't know what was wrong with this one image, but it's good now. Thx!

**Comment by bdw2292** [comment]
Great, thanks for checking.
